version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=artesian.settings_conf.dev
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
