# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 07:06
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('investor', django.db.models.manager.Manager()),
            ],
        ),
    ]
