# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0002_auto_20170930_0706'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
