# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 02:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0004_auto_20171001_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='current_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
